package com.fezda.spring;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class MyApplication {

	/**********************************
	 * 1. Add this parent element to the pom.xml
	 *    <parent>
	 *      <groupId>org.springframework.boot</groupId>
	 *      <artifactId>spring-boot-starter-parent</artifactId>
	 *      <version>2.7.5</version>
	 *      <relativePath/> <!-- lookup parent from repository -->
  	 *    </parent>
  	 *    
  	 * 2. Add this Dependency to the pom.xml
  	 *    <dependency>
	 *	    <groupId>org.springframework.boot</groupId>
	 *	    <artifactId>spring-boot-starter-web</artifactId>
	 *    </dependency>
	 *    
	 * 3. Create application class like this one
	 * 
	 * 4. Create a controller class like MyControlled.java Run this class as a Spring boot application
	 * 
	 * 5. Run the application class as a Spring Boot application (right click on application class in Eclipse, Run as, ...)
	 * 
	 * 6. Open browser at http://localhost:8080/test to see output generated by function mapped to /test
	 *********************************/
	public static void main(String[] args) {
		SpringApplication.run(MyApplication.class, args);
	}

}
