package com.fezda.spring;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class MyController {

	@Autowired
	JdbcTemplate jdbcT;
	
	@RequestMapping("/test")
	public String getAge () {
		return "string generated by spring app";
	}
	
	@RequestMapping("/db")
	public String getName () {
		String name = jdbcT.queryForObject("SELECT name FROM person where id = 1", String.class);
		return name;
	}
}
